import {centreOfElement,formatAddress,haversineM,sourceUrl} from './utils.mjs';
const text=tags=>`${tags.name||''} ${tags.operator||''} ${tags.brand||''}`.toLowerCase();const eq=(t,k,v)=>String(t[k]||'').toLowerCase()===v;const one=(t,k,vals)=>vals.includes(String(t[k]||'').toLowerCase());
function common(el,category,site){const p=centreOfElement(el);if(!p)return null;return{category,name:el.tags?.name||el.tags?.brand||'(unnamed mapped feature)',address:formatAddress(el.tags||{}),latitude:p.lat,longitude:p.lon,straightLineM:haversineM(site.latitude,site.longitude,p.lat,p.lon),osmType:el.type,osmId:el.id,sourceUrl:sourceUrl(el),tags:el.tags||{}};}
export function classifyElement(el,site){const tags=el.tags||{},name=text(tags),results=[];const add=(category,evidence)=>{const b=common(el,category,site);if(b)results.push({...b,evidence});};
if(eq(tags,'highway','bus_stop')||(eq(tags,'public_transport','platform')&&eq(tags,'bus','yes'))||(eq(tags,'public_transport','stop_position')&&eq(tags,'bus','yes')))add('bus_stop',{matched:'bus-stop-specific OSM tags'});
if(eq(tags,'amenity','bicycle_parking'))add('cycle_parking',{matched:'amenity=bicycle_parking'});
if(one(tags,'railway',['station','halt'])){const network=`${tags.network||''} ${tags.operator||''} ${tags.station||''}`.toLowerCase();if(network.includes('underground')||eq(tags,'station','subway'))add('underground_station',{matched:'rail station with Underground/subway evidence'});else if(network.includes('overground'))add('overground_station',{matched:'rail station with Overground evidence'});else if(network.includes('dlr')||network.includes('docklands'))add('dlr_station',{matched:'rail station with DLR evidence'});else add('national_rail_station',{matched:'railway=station/halt'});}
if(eq(tags,'railway','tram_stop'))add('tram_stop',{matched:'railway=tram_stop'});
if(one(tags,'amenity',['kindergarten','childcare']))add('nursery',{matched:`amenity=${tags.amenity}`});
if(eq(tags,'amenity','school')){const levels=String(tags['isced:level']||'');if(levels.split(';').includes('1')||/\b(primary|infant|junior|first school)\b/.test(name))add('primary_school',{matched:'school with primary evidence'});else if(levels.split(';').some(x=>['2','3'].includes(x))||/\b(secondary|high school|academy|comprehensive|upper school)\b/.test(name))add('secondary_school',{matched:'school with secondary evidence'});}
if(eq(tags,'amenity','college')&&!/\b(adult learning|adult education|learning and skills|training centre|training center)\b/.test(name)){if(/\bsixth form\b/.test(name))add('sixth_form',{matched:'amenity=college and sixth-form name'});else add('fe_college',{matched:'amenity=college; adult-learning exclusions passed'});}
if(eq(tags,'amenity','university'))add('university',{matched:'amenity=university'});
if(eq(tags,'shop','supermarket'))add('supermarket',{matched:'shop=supermarket'});if(eq(tags,'shop','convenience'))add('convenience_store',{matched:'shop=convenience'});if(eq(tags,'amenity','post_office')||eq(tags,'shop','post_office'))add('post_office',{matched:'post-office-specific tag'});if(eq(tags,'amenity','bank'))add('bank',{matched:'amenity=bank'});if(eq(tags,'amenity','atm'))add('cashpoint',{matched:'amenity=atm'});if(eq(tags,'amenity','fuel'))add('petrol_station',{matched:'amenity=fuel'});
if(eq(tags,'amenity','doctors')||one(tags,'healthcare',['general_practitioner','doctor']))add('gp_surgery',{matched:'GP/doctor-specific healthcare tag'});
if(eq(tags,'amenity','clinic')&&/\b(gp|surgery|medical centre|medical center|health centre|health center|general practice)\b/.test(name)&&!/\b(gym|fitness|wellbeing|sports|leisure)\b/.test(name))add('gp_surgery',{matched:'clinic tag plus controlled GP-name evidence'});
if(eq(tags,'amenity','pharmacy')||eq(tags,'healthcare','pharmacy'))add('pharmacy',{matched:'pharmacy-specific tag'});if(eq(tags,'amenity','dentist')||eq(tags,'healthcare','dentist'))add('dentist',{matched:'dentist-specific tag'});if(eq(tags,'amenity','hospital')||eq(tags,'healthcare','hospital'))add('hospital',{matched:'hospital-specific tag'});if(eq(tags,'healthcare','optometrist')||eq(tags,'shop','optician'))add('optician',{matched:'optician-specific tag'});
if(eq(tags,'amenity','restaurant'))add('restaurant',{matched:'amenity=restaurant'});if(eq(tags,'amenity','cafe'))add('cafe',{matched:'amenity=cafe'});if(one(tags,'amenity',['pub','bar']))add('pub_bar',{matched:`amenity=${tags.amenity}`});if(one(tags,'leisure',['fitness_centre','sports_centre']))add('gym_leisure',{matched:`leisure=${tags.leisure}`});if(one(tags,'leisure',['park','recreation_ground']))add('park_open_space',{matched:`leisure=${tags.leisure}`});if(eq(tags,'leisure','playground'))add('playground',{matched:'leisure=playground'});if(eq(tags,'amenity','library'))add('library',{matched:'amenity=library'});if(eq(tags,'amenity','community_centre'))add('community_centre',{matched:'amenity=community_centre'});if(eq(tags,'amenity','place_of_worship'))add('place_of_worship',{matched:'amenity=place_of_worship'});return results;}
export function classifyAll(elements,site){const byCategory=new Map();for(const el of elements){for(const c of classifyElement(el,site)){const list=byCategory.get(c.category)||[];list.push(c);byCategory.set(c.category,list);}}const nearest={};for(const [category,list] of byCategory.entries()){list.sort((a,b)=>a.straightLineM-b.straightLineM);nearest[category]=list[0];}return{nearest,byCategory};}
