import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {REQUEST_SCHEMA,COMPLETED_SCHEMA,FIELD_KEYS,buildResearchRequest,makeRecord,validateCompleted,mergeRecord,matchRecord,completedRecord} from '../assets/js/rail-knowledge.js';
const here=path.dirname(fileURLToPath(import.meta.url)),root=path.resolve(here,'..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const request=JSON.parse(read('tests/fixtures/sample-research-request.json'));
const completed=JSON.parse(read('tests/fixtures/sample-completed-research.json'));
const tests=[];const test=(name,fn)=>tests.push([name,fn]);
test('research request schema is correct',()=>assert.equal(request.schema,REQUEST_SCHEMA));
test('request contains explicit task instructions',()=>assert.ok(request.task.instructions.length>=9&&request.task.action));
test('task tells ChatGPT to research without asking',()=>assert.match(request.task.instructions.join(' '),/without asking/i));
test('route geometries are excluded',()=>assert.equal(JSON.stringify(request).includes('coordinates":[['),false));
for(const k of ['frequencyTotal','frequencyByDestination','servicePattern','journeyOpportunities','lines'])test(`${k} remains in schema`,()=>assert.ok(FIELD_KEYS.includes(k)));
test('completed sample validates',()=>assert.equal(validateCompleted(completed),true));
test('nested existingRecord completed layout validates and normalises',()=>{const base=structuredClone(completed.records[0]);base.identifiers={crs:'',naptan:'',tfl:'',other:'',osm:''};const nested={stationName:base.canonicalName,canonicalName:base.canonicalName,mode:base.mode,coordinates:base.coordinates,osm:{identifier:'node/123'},identifiers:{crs:'ABC',naptan:'9100ABC',tfl:'',other:'verified-id',osm:''},existingRecord:base};const envelope={schema:COMPLETED_SCHEMA,version:2,records:[nested]};assert.equal(validateCompleted(envelope),true);const n=completedRecord(nested);assert.ok(n.fields.manager);assert.equal(n.identifiers.crs,'ABC');assert.equal(n.identifiers.naptan,'9100ABC');assert.equal(n.identifiers.other,'verified-id');assert.equal(n.identifiers.osm,'node/123')});
test('invalid schema is rejected',()=>assert.throws(()=>validateCompleted({...completed,schema:'bad'})));
test('verified field requires source/date',()=>{const x=structuredClone(completed);x.records[0].fields.manager.source='';assert.throws(()=>validateCompleted(x))});
test('older verified data does not overwrite newer verified data',()=>{const a=makeRecord({name:'A',mode:'National Rail',crs:'AAA'}),b=makeRecord({name:'A',mode:'National Rail',crs:'AAA'});a.fields.manager={value:'New',status:'verified',source:'s',retrievalDate:'2026-07-14'};b.fields.manager={value:'Old',status:'verified',source:'s',retrievalDate:'2025-01-01'};assert.equal(mergeRecord(a,b).fields.manager.value,'New')});
test('reliable identifier matching has priority',()=>{const a=makeRecord({name:'Different',mode:'National Rail',crs:'ABC'});assert.equal(matchRecord({[a.key]:a},{name:'Other',mode:'National Rail',crs:'ABC',lat:0,lon:0}),a)});
test('all required files exist',()=>['index.html','assets/css/railway.css','assets/js/railway.js','assets/js/rail-knowledge.js','assets/vendor/leaflet/leaflet.css','assets/vendor/leaflet/leaflet.js','tests/fixtures/sample-research-request.json','tests/fixtures/sample-completed-research.json','README.md','RELEASE_NOTES.md','CHANGELOG.md'].forEach(f=>assert.ok(fs.existsSync(path.join(root,f)),f)));
test('address, map, discovery, routing and research controls remain present',()=>{const h=read('index.html'),j=read('assets/js/railway.js');['address','map','run','exportResearch','importResearch'].forEach(id=>assert.match(h,new RegExp(`id="${id}"`)));assert.match(j,/function initMap/);assert.match(j,/async function overpass/);assert.match(j,/async function route/);assert.match(j,/status:'estimated'/)});
test('modes remain separate',()=>{const j=read('assets/js/railway.js');['National Rail','London Underground','London Overground','DLR','Tram/light rail'].forEach(m=>assert.ok(j.includes(m)))});
test('build label is visible',()=>assert.ok(read('index.html').includes('RAIL-4.1.0-20260715')));
let passed=0;for(const [name,fn] of tests){try{await fn();console.log(`PASS ${name}`);passed++}catch(e){console.error(`FAIL ${name}: ${e.message}`);process.exitCode=1}}console.log(`\n${passed}/${tests.length} tests passed`);
