import assert from'node:assert/strict';import fs from'node:fs';import vm from'node:vm';import{validateCompleted,COMPLETED_SCHEMA,SCHEMA_VERSION}from'../modules/railway/assets/js/rail-knowledge.js';
const root=new URL('../',import.meta.url),read=p=>fs.readFileSync(new URL(p,root),'utf8'),json=p=>JSON.parse(read(p));let passed=0;function test(name,fn){try{fn();console.log('PASS '+name);passed++}catch(e){console.error('FAIL '+name+': '+e.message);process.exitCode=1}}
const store=new Map(),storage={getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v),removeItem:k=>store.delete(k)},context={window:{dispatchEvent(){}},localStorage:storage,sessionStorage:storage,location:{pathname:'/',href:'http://localhost/'},performance:{now:()=>0},CustomEvent:class{},Set,Map,Promise,Date,URL,confirm:()=>false,fetch:async()=>{throw Error('not used')},atob:globalThis.atob,btoa:globalThis.btoa,decodeURIComponent,encodeURIComponent,unescape};vm.createContext(context);vm.runInContext(read('assets/js/shared-library.js'),context);
test('Dashboard links Library Manager',()=>assert.match(read('index.html'),/modules\/library-manager\//));
test('all repository shared masters remain intact',()=>assert.deepEqual(['rail','bus-stop','bus-route'].map(n=>json('data/knowledge/'+n+'-library.json').records.length),[57,37,16]));
test('same route number in different areas has different identity',()=>{const key=context.window.TPTSharedLibrary.key,path=context.window.TPTSharedLibrary.paths.busRoutes,a={routeNumber:'1',operator:'Example',routeOrigin:'A',routeDestination:'B',geographicContext:'London'},b={routeNumber:'1',operator:'Example',routeOrigin:'C',routeDestination:'D',geographicContext:'Leeds'};assert.notEqual(key(path,a),key(path,b))});
test('route number alone is insufficient identity',()=>{const key=context.window.TPTSharedLibrary.key,path=context.window.TPTSharedLibrary.paths.busRoutes;assert.notEqual(key(path,{routeNumber:'7',operator:'A',routeOrigin:'North',routeDestination:'South'}),key(path,{routeNumber:'7',operator:'A',routeOrigin:'East',routeDestination:'West'}))});
test('Rail placeholder research is rejected',()=>{const record={name:'Test',mode:'National Rail',identifiers:{crs:'TST'},fields:{manager:{value:'Check National Rail',status:'verified',source:'https://example.test',retrievalDate:'2026-07-17'}}};assert.throws(()=>validateCompleted({schema:COMPLETED_SCHEMA,version:SCHEMA_VERSION,records:[record]}),/placeholder/)});
test('manager has mode-specific request paths and import report',()=>{const s=read('modules/library-manager/assets/library-manager.js');assert.match(s,/rail-library-research-request/);assert.match(s,/bus-stop-library-research-request/);assert.match(s,/bus-route-library-research-request/);assert.match(s,/rejected placeholder fields/)});
test('manager has controlled publication deletion and exports',()=>{const h=read('modules/library-manager/index.html'),s=read('modules/library-manager/assets/library-manager.js');['Export filtered CSV','Export complete CSV','Export complete JSON backup'].forEach(x=>assert.ok(h.includes(x)));assert.match(s,/publishRecords/);assert.match(s,/deleteRecord/)});
console.log(`\n${passed} Library Manager tests passed.`);
