import assert from'node:assert/strict';import fs from'node:fs';await import('../assets/js/research-quality.js');const q=globalThis.TPTResearchQuality;let passed=0;function test(name,fn){try{fn();console.log('PASS '+name);passed++}catch(e){console.error('FAIL '+name+': '+e.message);process.exitCode=1}}
const source={url:'https://tfl.gov.uk/station/example/facilities',title:'Example station facilities',publisher:'Transport for London',retrievalDate:'2026-07-22'};
const railFields=['manager','operators','lines','frequencyTotal','frequencyByDestination','servicePattern','frequency','destinations','journeyOpportunities','cycleParking','stepFree','ticketing','waiting','toilets','carParking','notes'];
const rail=(key,value,status='verified',extra={})=>({name:'Plaistow',mode:'London Underground',fields:{[key]:{value,status,source:source.url,sourceTitle:source.title,publisher:source.publisher,retrievalDate:source.retrievalDate,...extra}}});
test('A lazy Rail response is rejected with field detail',()=>{const r=q.analyseRecord(rail('cycleParking','See the TfL website for cycle parking information.'),'rail');assert.equal(r.quality,'Poor legacy record');assert.equal(r.publishable,false);assert.match(r.issues[0].message,/Plaistow — cycleParking/)});
test('B professional-sounding lazy response is insufficient',()=>{const r=q.analyseRecord(rail('cycleParking','No published cycle-parking quantity was identified on the current TfL station page.'),'rail');assert.equal(r.publishable,false);assert.match(r.issues[0].reason,/placeholder/)});
test('C exhaustive unresolved is retained for review but not publishable',()=>{const audit={sourcesChecked:[source,{url:'https://www.nationalrail.co.uk/stations/example/',title:'Example station',publisher:'National Rail',retrievalDate:'2026-07-22'}],sectionsChecked:['Station facilities','Cycle storage'],searchTermsChecked:['cycle','bicycle','bike','racks','stands'],reason:'Neither authoritative page or its linked facility material states a defensible provision or quantity.'},record=rail('cycleParking','not_publicly_available_after_exhaustive_search','needs_review',{researchAudit:audit});railFields.filter(x=>x!=='cycleParking').forEach(key=>record.fields[key]={value:key==='frequencyByDestination'?[]:'Verified fixture value',status:'verified',source:source.url,sourceTitle:source.title,publisher:source.publisher,retrievalDate:source.retrievalDate});record.fields.frequencyByDestination.value=[{destination:'Example',tph:2}];const r=q.analyseRecord(record,'rail');assert.equal(r.quality,'Complete but requires review');assert.equal(r.publishable,false);assert.equal(r.issues.length,0)});
test('D verified negative fact is accepted',()=>{const r=q.analyseRecord(rail('toilets','No toilets are provided.'),'rail');assert.equal(r.issues.length,0);assert.equal(r.fields[0].state,'accepted')});
test('E lazy Bus response is rejected',()=>{const route={routeNumber:'10',operator:'Example Bus',routeOrigin:'North',routeDestination:'South',servicePattern:'Check the operator timetable for current frequencies.',sources:[source],retrievalDate:'2026-07-22',verificationStatus:'verified'},r=q.analyseRecord(route,'bus-route');assert.equal(r.publishable,false);assert.ok(r.issues.some(x=>x.field==='servicePattern'))});
test('F route-number-only ambiguity is blocked clearly',()=>{const data={stopRecords:[],stopRouteRecords:[],routeRecords:[{routeNumber:'1',operator:'Example',routeOrigin:'A',routeDestination:'B',geographicContext:'Unknown'}]},requested=[{routeNumber:'1',operator:'Example',routeOrigin:'A',routeDestination:'B',geographicContext:'London'},{routeNumber:'1',operator:'Other',routeOrigin:'C',routeDestination:'D',geographicContext:'Leeds'}];assert.throws(()=>q.validateBusCompleted(data,{requestedRoutes:requested,reject:true}),/multiple geographical routes/)});
test('G legacy record loads, is poor and is not mutated',()=>{const legacy=rail('cycleParking','See website'),before=JSON.stringify(legacy),r=q.analyseRecord(legacy,'rail');assert.equal(r.quality,'Poor legacy record');assert.equal(r.publishable,false);assert.equal(JSON.stringify(legacy),before)});
test('H shared standards remain mode-specific and schema-neutral',()=>{const railRequest=q.enhanceRailRequest({schema:'tpt-rail-research-request-v2'}),busRequest=q.enhanceBusRequest({schema:'tpt.bus-research'},'bus-route'),railModule=fs.readFileSync(new URL('../modules/railway/assets/js/railway.js',import.meta.url),'utf8'),busModule=fs.readFileSync(new URL('../modules/bus/assets/js/bus-core.js',import.meta.url),'utf8'),manager=fs.readFileSync(new URL('../modules/library-manager/assets/library-manager.js',import.meta.url),'utf8');assert.equal(railRequest.schema,'tpt-rail-research-request-v2');assert.equal(busRequest.schema,'tpt.bus-research');assert.equal(railRequest.researchStandard.build,busRequest.researchStandard.build);assert.notEqual(railRequest.researchStandard.mode,busRequest.researchStandard.mode);assert.match(railModule,/TPTResearchQuality\.enhanceRailRequest/);assert.match(busModule,/TPTResearchQuality\.enhanceBusRequest/);assert.match(manager,/TPTResearchQuality\.enhance(?:Rail|Bus)Request/)});
console.log(`\n${passed} research-quality fixtures passed.`);
