import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';

const code=fs.readFileSync(new URL('../assets/js/research-workflow.js',import.meta.url),'utf8');
const context={URL,Map,Set,Date,console};context.globalThis=context;vm.runInNewContext(code,context);
const W=context.TPTResearchWorkflow;
const test=(name,fn)=>{try{fn();console.log('PASS',name)}catch(error){console.error('FAIL',name);throw error}};
const stop=(id,pair='')=>({stopName:id,naptanCode:id,pairedStopGroup:pair});
const route=(number,area='Hertford')=>({routeNumber:String(number),transportAuthority:area,operator:'Operator',routeOrigin:'A',routeDestination:'B',geographicContext:area});
const source={url:'https://operator.example/timetables/route-1.pdf',title:'Route 1 timetable',publisher:'Operator',retrievalDate:'2026-07-22'};
const completeRoute=Object.assign(route(1),{principalLocationsServed:['C'],mondayFridayOperatingPeriod:'06:00-23:00',saturdayOperatingPeriod:'07:00-23:00',sundayOperatingPeriod:'08:00-22:00',servicePattern:'Every 30 minutes',sources:[source],retrievalDate:'2026-07-22',verificationStatus:'verified'});
const relation=(id,r)=>({naptanCode:id,routeNumber:r.routeNumber,operator:r.operator,routeOrigin:r.routeOrigin,routeDestination:r.routeDestination,geographicContext:r.geographicContext,compositeRouteKey:W.routeKey(r),directionFromStop:'Northbound',stopSpecificDestination:'B',mondayFridayOperatingPeriod:'06:00-23:00',saturdayOperatingPeriod:'07:00-23:00',sundayOperatingPeriod:'08:00-22:00',typicalWeekdayBusesPerHour:2,saturdayBusesPerHour:2,sundayBusesPerHour:1,servicePattern:'Every 30 minutes',journeyOpportunities:'Direct journeys to B',sources:[source],retrievalDate:'2026-07-22',verificationStatus:'verified'});

test('Rail 1-5 is one safe stable batch and 6 is two',()=>{for(let n=1;n<=5;n++)assert.equal(W.railPlan(Array.from({length:n},(_,i)=>({name:'Station '+i,identifiers:{crs:'S0'+i}}))).batches.length,1);const records=Array.from({length:6},(_,i)=>({name:'Station '+i,identifiers:{crs:'S0'+i}})),a=W.railPlan(records),b=W.railPlan(records.slice().reverse());assert.equal(a.batches.length,2);assert.ok(a.batches.every(x=>x.records.length<=5));assert.deepEqual(JSON.parse(JSON.stringify(a.batches.map(x=>[x.batchId,x.selectedCanonicalRecordKeys]))),JSON.parse(JSON.stringify(b.batches.map(x=>[x.batchId,x.selectedCanonicalRecordKeys]))));});
test('Bus Phase 1 isolates pairs and limits standalone stops to two',()=>{const p=W.busPhase1Plan([stop('A','pair-a'),stop('B','pair-a'),stop('C','pair-b'),stop('D','pair-b'),stop('E'),stop('F'),stop('G')]);assert.equal(p.batches.length,4);assert.ok(p.batches.every(x=>x.stops.length<=2));assert.deepEqual(JSON.parse(JSON.stringify(p.batches.map(x=>x.stops.map(y=>y.naptanCode)))),[['A','B'],['C','D'],['E','F'],['G']]);});
test('Bus Phase 2 adaptively packs six routes and twelve relationships',()=>{const routes=Array.from({length:9},(_,i)=>route(i+1)),links=routes.flatMap(r=>[relation('A',r),relation('B',r)]),p=W.busPhase2Plan(routes,links,{stops:[stop('A'),stop('B')]});assert.equal(p.batches.length,2);assert.ok(p.batches.every(x=>x.routeKeys.length<=6&&x.relationships.length<=12));assert.deepEqual(JSON.parse(JSON.stringify(p.batches.map(x=>[x.routeKeys.length,x.relationships.length]))),[[6,12],[3,6]]);});
test('Relevant subset excludes unrelated same-number and other-project data',()=>{const h=route(10,'Hertford'),l=route(10,'London'),hr=relation('A',h),lr=relation('Z',l),result=W.relevantSubset({stops:[stop('A'),stop('Z')],routes:[h,l],stopRoutes:[hr,lr]},[stop('A')],{routeKeys:[W.routeKey(h)]});assert.equal(result.stops.length,1);assert.equal(result.routes.length,1);assert.equal(result.routes[0].geographicContext,'Hertford');assert.equal(result.stopRoutes.length,1);});
test('Missing values never become no service without direct evidence',()=>{assert.equal(W.displayService('',{}),'Not established');assert.equal(W.displayService('No Sunday service',{verificationStatus:'verified'}),'Requires review');assert.equal(W.displayService('No Sunday service',{verificationStatus:'verified',sources:[source]}),'No Sunday service');});
test('Completeness requires service fields, relationships and direct evidence',()=>{assert.deepEqual(JSON.parse(JSON.stringify(W.missingRoute(completeRoute))),[]);assert.ok(W.missingRoute(route(2)).includes('mondayFridayOperatingPeriod'));assert.deepEqual(JSON.parse(JSON.stringify(W.missingRelationship(relation('A',completeRoute)))),[]);});
test('Assessment status cannot be complete with quarantine or global-only routes',()=>{assert.equal(W.assessmentStatus({selectedStops:[stop('A')],routes:[],relationships:[],phase1:{batches:[]},phase2:{batches:[]}}),'Route/service research required');assert.equal(W.assessmentStatus({selectedStops:[stop('A')],routes:[completeRoute],relationships:[relation('A',completeRoute)],quarantined:[{}],phase1:{batches:[]},phase2:{batches:[]}}),'Research incomplete');assert.equal(W.assessmentStatus({selectedStops:[stop('A')],routes:[completeRoute],relationships:[relation('A',completeRoute)],phase1:{batches:[]},phase2:{batches:[]}}),'Research complete and ready for output');});
test('Batch state survives regeneration and confirmed cleanup is exact',()=>{const records=Array.from({length:6},(_,i)=>({name:'Station '+i,identifiers:{crs:'S0'+i}})),a=W.railPlan(records);W.markBatch(a,a.batches[0].batchId,'imported','done.json');const b=W.railPlan(records,{savedState:W.savedPlan(a)});assert.equal(b.batches[0].status,'imported');const c=W.cleanupConfirmed(records,[W.railKey(records[0])],W.railKey);assert.equal(c.removed.length,1);assert.equal(c.retained.length,5);});
test('One Rail correction request groups several stations and preserves accepted fields',()=>{const fields=['lines','frequencyTotal','servicePattern'],data={batchMetadata:{requestGroupId:'g',batchId:'b'},records:[{existingRecord:{name:'One',mode:'Rail',identifiers:{crs:'ONE'},coordinates:{lat:1,lon:1},fields:{lines:{value:'accepted'},frequencyTotal:{value:'bad'}}}},{existingRecord:{name:'Two',mode:'Rail',identifiers:{crs:'TWO'},coordinates:{lat:2,lon:2},fields:{servicePattern:{value:'bad'}}}}]},failures=[{record:'One',field:'frequencyTotal',reason:'generic URL'},{record:'Two',field:'servicePattern',reason:'missing publisher'}],request=W.railCorrection(data,failures,fields);assert.equal(request.records.length,2);assert.equal(request.records[0].failedFields.length,1);assert.deepEqual(JSON.parse(JSON.stringify(request.records[0].acceptedFieldsMustRemainUnchanged)),['lines','servicePattern']);assert.equal(request.records[0].originalRecord.fields.lines.value,'accepted');});

console.log('Research workflow behavioural tests passed.');
