import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const workflow = fs.readFileSync(path.join(root, '.github/workflows/atlas-bus-data-refresh.yml'), 'utf8');
const publication = fs.readFileSync(path.join(root, 'tools/atlas-data-publication/publication.mjs'), 'utf8');
const validator = fs.readFileSync(path.join(root, 'tools/atlas-data-publication/validate-publication.mjs'), 'utf8');
const lkg = fs.readFileSync(path.join(root, 'tools/atlas-data-publication/fetch-last-known-good.mjs'), 'utf8');
const selectBank = fs.readFileSync(path.join(root, 'tools/atlas-data-publication/select-bank.mjs'), 'utf8');
const sourceConfig = fs.readFileSync(path.join(root, 'src/atlas/infrastructure/atlas-data-sources.mjs'), 'utf8');
const snapshot = fs.readFileSync(path.join(root, 'tools/atlas-data-publication/publish-snapshot.mjs'), 'utf8');
const checkout = fs.readFileSync(path.join(root, 'tools/atlas-data-publication/checkout-bank.mjs'), 'utf8');
const release = JSON.parse(fs.readFileSync(path.join(root, 'atlas/config/atlas-release.json'), 'utf8'));

assert.equal(release.version, '2.0.0-alpha.15');
assert.equal(release.build, 'ATLAS-2.0.0-alpha.15-20260914');
assert.match(workflow, /workflow_dispatch/);
assert.match(workflow, /Manual non-main execution is diagnostic-only/);
assert.match(workflow, /ATLAS_TNDS_BANKS_JSON/);
assert.match(workflow, /select-bank\.mjs/);
assert.match(workflow, /checkout-bank\.mjs/);
assert.match(workflow, /publish-bank\.mjs/);
assert.match(workflow, /Wait for every candidate-bank root publication/);
assert.match(workflow, /validate-publication\.mjs/);
assert.match(workflow, /timeout-minutes: 180/);
assert.match(workflow, /github\.ref == 'refs\/heads\/main' && inputs\.measure_only != true/);
assert.doesNotMatch(workflow.slice(0, workflow.indexOf('jobs:')), /TNDS_USERNAME|TNDS_PASSWORD/);
assert.match(publication, /atlas-data-sources-v2/);
assert.match(publication, /atlas-reference-data-publication-v4/);
assert.match(publication, /exact-minimax/);
assert.match(publication, /activeTndsBank/);
assert.match(publication, /rollbackToOppositeBank/);
assert.match(publication, /createRollbackPublicationSnapshot/);
assert.match(validator, /expectedBankId/);
assert.match(validator, /exact candidate allocation/);
assert.match(lkg, /active-publication\.json/);
assert.match(lkg, /rollbackBank/);
assert.match(selectBank, /selectOppositeTndsBank/);
assert.match(sourceConfig, /pathMap/);
assert.match(sourceConfig, /fileUrl/);
assert.doesNotMatch(snapshot, /return \{ branch, commit, remote \}/);
assert.match(checkout, /GIT_ASKPASS/);
assert.doesNotMatch(checkout, /x-access-token:\$\{encodeURIComponent\(token\)\}/);
console.log('PASS BUS-RECOVERY-0D.3A workflow, dual-bank contract, timeout, diagnostic-only, rollback and credential-output checks.');
