import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const workflow = fs.readFileSync(path.join(root, '.github/workflows/atlas-bus-data-refresh.yml'), 'utf8');
const publication = fs.readFileSync(path.join(root, 'tools/atlas-data-publication/publication.mjs'), 'utf8');
const validator = fs.readFileSync(path.join(root, 'tools/atlas-data-publication/validate-publication.mjs'), 'utf8');
const lkg = fs.readFileSync(path.join(root, 'tools/atlas-data-publication/fetch-last-known-good.mjs'), 'utf8');
const selectBank = fs.readFileSync(path.join(root, 'tools/atlas-data-publication/select-bank.mjs'), 'utf8');
const sourceConfig = fs.readFileSync(path.join(root, 'src/atlas/infrastructure/atlas-data-sources.mjs'), 'utf8');
const snapshot = fs.readFileSync(path.join(root, 'tools/atlas-data-publication/publish-snapshot.mjs'), 'utf8');
const checkout = fs.readFileSync(path.join(root, 'tools/atlas-data-publication/checkout-bank.mjs'), 'utf8');
const wait = fs.readFileSync(path.join(root, 'tools/atlas-data-publication/wait-for-bank.mjs'), 'utf8');
const preflight = fs.readFileSync(path.join(root, 'tools/atlas-data-publication/preflight-publication.mjs'), 'utf8');
const checkpoint = fs.readFileSync(path.join(root, 'tools/atlas-data-publication/candidate-checkpoint.mjs'), 'utf8');
const release = JSON.parse(fs.readFileSync(path.join(root, 'atlas/config/atlas-release.json'), 'utf8'));

assert.equal(release.version, '2.0.0-alpha.15');
assert.equal(release.build, 'ATLAS-2.0.0-alpha.15-20260914');
assert.match(workflow, /workflow_dispatch/);
assert.match(workflow, /prepared_schema:/);
assert.match(workflow, /default: v1/);
assert.match(workflow, /- v1[\s\S]*- v2/);
assert.match(workflow, /Prepared-data v2 is diagnostic-only/);
assert.match(workflow, /--prepared-schema/);
assert.match(workflow, /inputs\.prepared_schema \|\| 'v1'/);
assert.match(workflow, /FORCE_REFRESH:.*inputs\.prepared_schema == 'v2'/);
assert.match(workflow, /Run national v2 diagnostic and same-window shadow parity/);
assert.match(workflow, /national_v2_diagnostic\.py/);
assert.match(workflow, /actions\/upload-artifact@v4/);
assert.match(workflow, /name: atlas-v2-national-diagnostic-\$\{\{ github\.run_id \}\}/);
assert.match(workflow, /if: always\(\) && inputs\.prepared_schema == 'v2'/);
assert.match(workflow, /Raw authoritative source material must not enter the diagnostic artifact/);
assert.match(workflow, /Manual non-main execution is diagnostic-only/);
assert.match(workflow, /ATLAS_TNDS_BANKS_JSON/);
assert.match(workflow, /select-bank\.mjs/);
assert.match(workflow, /checkout-bank\.mjs/);
assert.match(workflow, /publish-bank\.mjs/);
assert.match(workflow, /persist-credentials: false/);
assert.match(workflow, /preflight-publication\.mjs/);
assert.match(workflow, /wait-for-bank\.mjs --config/);
assert.ok(workflow.indexOf('preflight-publication.mjs') < workflow.indexOf('Acquire and build validated Bus\/TNDS candidate'));
assert.match(workflow, /Wait for every candidate-bank root publication/);
assert.match(workflow, /validate-publication\.mjs/);
assert.match(workflow, /timeout-minutes: 180/);
assert.doesNotMatch(workflow, /github\.run_started_at/);
assert.match(workflow, /actions\/cache\/restore@v4/);
assert.match(workflow, /actions\/cache\/save@v4/);
assert.match(workflow, /resume_checkpoint_run_id/);
assert.match(workflow, /ATLAS_CHECKPOINT_PRODUCER_RUN_ID: \$\{\{ inputs\.resume_checkpoint_run_id \|\| github\.run_id \}\}/);
assert.match(workflow, /ATLAS_CURRENT_CANDIDATE_CACHE_KEY: atlas-verified-candidate-checkpoint-v2-\$\{\{ github\.run_id \}\}/);
assert.match(workflow, /ATLAS_CANDIDATE_CACHE_KEY: atlas-verified-candidate-checkpoint-v2-\$\{\{ inputs\.resume_checkpoint_run_id \|\| github\.run_id \}\}/);
assert.doesNotMatch(workflow, /restore-keys:/);
assert.match(workflow, /candidate-checkpoint\.mjs --restore/);
assert.match(workflow, /candidate-checkpoint\.mjs --create/);
assert.match(workflow, /--gate-candidate-validation passed/);
assert.match(workflow, /--gate-deterministic-checks passed/);
assert.match(workflow, /--gate-capacity-measurement passed/);
assert.match(workflow, /candidate-checkpoint\.mjs --timestamp-only/);
assert.match(workflow, /path: \|[\s\S]*pages-site\/atlas\/data\/bus[\s\S]*pages-site\/atlas\/data\/bus-tnds[\s\S]*pages-site\/atlas\/data\/status[\s\S]*atlas-candidate-measurement\.json[\s\S]*verified-candidate\.json/);
const cacheContract = workflow.slice(workflow.indexOf('uses: actions/cache/restore@v4'), workflow.indexOf('Complete diagnostic-only run'));
assert.doesNotMatch(cacheContract, /path: pages-site\s/);
assert.match(workflow, /exact cache entry was invalid and remains immutable/);
assert.ok(workflow.indexOf('Verify restored candidate checkpoint') < workflow.indexOf('Acquire and build validated Bus\/TNDS candidate'));
assert.ok(workflow.indexOf('Record checkpoint resume decision') < workflow.indexOf('Acquire and build validated Bus\/TNDS candidate'));
assert.ok(workflow.indexOf('Create verified candidate checkpoint') < workflow.indexOf('Check out Bus reference-data publication repository'));
assert.match(checkpoint, /atlas-verified-candidate-checkpoint-v2/);
assert.match(checkpoint, /candidateGenerationTimestamp/);
assert.match(checkpoint, /candidateGenerationCompatibilityFingerprint/);
assert.match(checkpoint, /candidateFreshness/);
assert.match(checkpoint, /producerRunId/);
assert.match(checkpoint, /statusManifestSha256/);
assert.match(checkpoint, /productionEligible/);
assert.match(checkpoint, /manifestSha256/);
assert.match(checkpoint, /assertPublicationCapacity/);
assert.match(checkpoint, /cacheExactHit/);
assert.match(checkpoint, /measurePublicationTree/);
assert.match(workflow, /github\.ref == 'refs\/heads\/main' && inputs\.measure_only != true/);
assert.doesNotMatch(workflow.slice(0, workflow.indexOf('jobs:')), /TNDS_USERNAME|TNDS_PASSWORD/);
assert.match(publication, /atlas-data-sources-v2/);
assert.match(publication, /atlas-reference-data-publication-v4/);
assert.match(publication, /exact-minimax/);
assert.match(publication, /activeTndsBank/);
assert.match(publication, /rollbackToOppositeBank/);
assert.match(publication, /createRollbackPublicationSnapshot/);
assert.match(validator, /expectedBankId/);
assert.match(validator, /exact candidate allocation/);
assert.match(lkg, /active-publication\.json/);
assert.match(lkg, /rollbackBank/);
assert.match(selectBank, /selectOppositeTndsBank/);
assert.match(sourceConfig, /pathMap/);
assert.match(sourceConfig, /fileUrl/);
assert.doesNotMatch(snapshot, /return \{ branch, commit, remote \}/);
assert.match(snapshot, /createTransientGitAuth/);
assert.match(snapshot, /GIT_ASKPASS/);
assert.match(snapshot, /ls-remote/);
assert.match(snapshot, /force-with-lease/);
assert.match(snapshot, /publicRemote/);
assert.match(workflow, /Publish Bus and every candidate TNDS root[\s\S]*ATLAS_REFERENCE_DATA_TOKEN/);
assert.match(workflow, /Publish validated Bus bounded snapshot[\s\S]*ATLAS_REFERENCE_DATA_TOKEN/);
assert.match(checkout, /ATLAS_REFERENCE_DATA_TOKEN/);
assert.match(checkout, /git.*init/);
assert.match(checkout, /preparedWithoutFetch/);
assert.doesNotMatch(checkout, /git['"]?, \['clone'/);
assert.doesNotMatch(workflow, /checkout-bank\.mjs[^\n]*--token/);
assert.match(wait, /publicationVersion/);
assert.match(wait, /expectedBankId/);
assert.match(wait, /expectedRootId/);
assert.match(wait, /expectedSlot/);
assert.match(preflight, /exactly two banks/);
assert.match(preflight, /ls-remote/);
assert.match(preflight, /push permission/);
assert.match(preflight, /atlas-publication-site\.json/);
assert.doesNotMatch(preflight, /bootstrapAllowed/);
assert.match(preflight, /health threshold/);
assert.match(publication, /SAFE_GIT_BLOB_LIMIT_BYTES/);
assert.match(publication, /atlas-publication-site\.json/);
console.log('PASS BUS-RECOVERY-0D.3C workflow, version-aware wait, preflight, no-full-clone preparation, rollback and transient-auth checks.');
