import assert from 'node:assert/strict';
import fs from 'node:fs';

const html = fs.readFileSync(new URL('../../atlas/index.html', import.meta.url), 'utf8');
const app = fs.readFileSync(new URL('../../atlas/assets/js/app.mjs', import.meta.url), 'utf8');
assert.match(html, /2\.0\.0-alpha\.12/);
assert.match(html, /ATLAS-2\.0\.0-alpha\.12-20260909/);
for (const id of ['dataStatusMessage', 'preparedDataDate', 'naptanDataState', 'bodsDataState', 'tndsDataDate', 'tflDataState', 'updateBusData', 'refreshDataStatus', 'recommendedSelection', 'selectAllRows', 'clearAllRows', 'toggleDetailedEvidence', 'serviceDetailPanel', 'assessmentScope', 'radius']) assert.match(html, new RegExp(`id="${id}"`));
assert.match(html, /<th>Include<\/th>/);
assert.match(html, /<th>Timetable evidence<\/th>/);
assert.match(html, /<th>Typical frequency<\/th>/);
assert.match(html, /<th>Operating period<\/th>/);
assert.match(app, /timetableEvidence/);
assert.match(app, /Typical frequency/);
assert.match(app, /syncRadiusCircle/);
assert.match(app, /syncRadiusCircle\(result\.provenance\.stops\?\.actualDiscoveryRadiusMetres/);
assert.match(app, /TFL_SAFE_DETAILED_PAIR_LIMIT/);
assert.match(app, /This assessment may require staged TfL requests/);
assert.match(app, /createTflRequestScheduler/);
assert.match(app, /requestScheduler: tflRequestScheduler/);
assert.match(app, /detailedEvidenceVisible/);
assert.match(app, /The assessment radius changed\. Build the Bus assessment again to update the evidence\./);
assert.match(app, /pendingScopeDiscovery/);
assert.match(app, /discoveryOverride/);
assert.match(app, /pendingScopeContext\?\.site === confirmedSite/);
assert.match(html, /placeholder="Enter site address or name"/);
assert.doesNotMatch(html, /value="33 Westow Street, Crystal Palace, London"/);
assert.doesNotMatch(html, /33 Westow Street, Crystal Palace, London/);
assert.doesNotMatch(app, /Site selected on map/);
assert.doesNotMatch(app, /No additional principal locations identified/);
assert.match(app, /Try a different search, or choose the assessment point on the map instead/);
assert.doesNotMatch(app, /Your description is still recorded/);
assert.match(app, /buildServicePresentation/);
assert.match(app, /__atlas-review\/update-bus-data/);
assert.doesNotMatch(app, /Traveline (username|password)/i);
assert.match(app, /Checked successfully — no changes detected/);
assert.match(app, /Live source — checked when a London assessment is run/);
assert.match(html, /Traveline National Dataset \(TNDS\)/);
assert.match(html, /Open Government Licence v3\.0/);
console.log('PASS Bus UI contract - Alpha.12 status, selection, full-week frequency, radius map and local maintenance controls are exposed without browser credentials.');
