import assert from 'node:assert/strict';
import fs from 'node:fs';

const html = fs.readFileSync(new URL('../../atlas/index.html', import.meta.url), 'utf8');
const app = fs.readFileSync(new URL('../../atlas/assets/js/app.mjs', import.meta.url), 'utf8');
assert.match(html, /2\.0\.0-alpha\.9/);
assert.match(html, /ATLAS-2\.0\.0-alpha\.9-20260908/);
for (const id of ['dataStatusMessage', 'preparedDataDate', 'naptanDataState', 'bodsDataState', 'tndsDataDate', 'tflDataState', 'updateBusData', 'refreshDataStatus', 'recommendedSelection', 'selectAllRows', 'clearAllRows']) assert.match(html, new RegExp(`id="${id}"`));
assert.match(html, /<th>Include<\/th>/);
assert.match(html, /placeholder="Enter site address or name"/);
assert.doesNotMatch(html, /value="33 Westow Street, Crystal Palace, London"/);
assert.doesNotMatch(html, /33 Westow Street, Crystal Palace, London/);
assert.doesNotMatch(app, /Site selected on map/);
assert.doesNotMatch(app, /No additional principal locations identified/);
assert.match(app, /Try a different search, or choose the assessment point on the map instead/);
assert.doesNotMatch(app, /Your description is still recorded/);
assert.match(app, /buildServicePresentation/);
assert.match(app, /__atlas-review\/update-bus-data/);
assert.doesNotMatch(app, /Traveline (username|password)/i);
assert.match(app, /Checked successfully — no changes detected/);
assert.match(app, /Live source — checked when a London assessment is run/);
assert.match(html, /Traveline National Dataset \(TNDS\)/);
assert.match(html, /Open Government Licence v3\.0/);
console.log('PASS Bus UI contract - Alpha.9 status, selection and local maintenance controls are exposed without browser credentials.');
