await import('./site.test.mjs');
await import('./site-selector.test.mjs');
await import('./evidence.test.mjs');
await import('./source-adapter.test.mjs');
await import('./nominatim-geocoding-adapter.test.mjs');
await import('./tfl-bus-stop-adapter.test.mjs');
await import('./geography.test.mjs');
await import('./naptan-bus-stop-adapter.test.mjs');
await import('./bus-stop-discovery.test.mjs');
await import('./legacy-isolation.test.mjs');
await import('./review-environment.test.mjs');
console.log('ATLAS Alpha.3 deterministic suite passed.');
