import assert from 'node:assert/strict';
import { parseTndsOperatingProfile, parseTndsTransXchange, parseTndsTransXchangeServices } from '../../src/atlas/adapters/tnds-transxchange-adapter.mjs';
import { mergeBusTimetableSources } from '../../src/atlas/domain/bus-timetable-merge.mjs';
const xml = `<TransXChange SchemaVersion="2.5"><Operators><Operator id="OP1"><OperatorCode>OP1</OperatorCode><TradingName>Example</TradingName></Operator></Operators><Services><Service><ServiceCode>S1</ServiceCode><LineName>231</LineName><OperatingPeriod><StartDate>2026-08-31</StartDate><EndDate>2027-07-31</EndDate></OperatingPeriod><StandardService><Origin>A</Origin><Destination>B</Destination></StandardService><OperatingProfile><MondayToFriday>true</MondayToFriday></OperatingProfile></Service></Services><StopPoints><AnnotatedStopPointRef><StopPointRef>021013518</StopPointRef><CommonName>Woodside Road</CommonName></AnnotatedStopPointRef></StopPoints><VehicleJourneys><VehicleJourney><VehicleJourneyCode>V1</VehicleJourneyCode><JourneyPatternRef>JP1</JourneyPatternRef><DepartureTime>25:10:00</DepartureTime><OperatingProfile><MondayToFriday>true</MondayToFriday></OperatingProfile></VehicleJourney></VehicleJourneys><JourneyPatterns><JourneyPattern id="JP1"><Direction>outbound</Direction><DestinationDisplay>B</DestinationDisplay></JourneyPattern></JourneyPatterns></TransXChange>`;
const parsed = parseTndsTransXchange(xml, { region: 'SE', sourceArchive: 'TNDS-SE-v2.5.zip' });
assert.equal(parsed.routeNumber, '231'); assert.equal(parsed.operator, 'Example'); assert.equal(parsed.validFrom, '2026-08-31'); assert.equal(parsed.stopSchedules['021013518'].monday[0], 1510); assert.equal(parsed.source.schemaVersion, '2.5');
assert.deepEqual(parsed.calendarEvidence[0].daysOfWeek, ['monday', 'tuesday', 'wednesday', 'thursday', 'friday']);
assert.equal(parsed.serviceNotes.length, 0, 'ordinary weekday service does not acquire a school-day qualification');
const schoolProfile = parseTndsOperatingProfile('<OperatingProfile><ServicedOrganisationDayType>Schooldays</ServicedOrganisationDayType><DaysOfOperation>Monday, Tuesday, Wednesday, Thursday, Friday</DaysOfOperation></OperatingProfile>');
assert.deepEqual(schoolProfile.daysOfWeek, ['monday', 'tuesday', 'wednesday', 'thursday', 'friday']);
assert.equal(schoolProfile.schoolDayOnly, true);
assert.equal(schoolProfile.daysOfWeek.includes('saturday'), false, 'school profile does not fabricate weekend operation');
assert.match(parseTndsOperatingProfile('<OperatingProfile><ServicedOrganisationDayType>TermTime</ServicedOrganisationDayType><MondayToFriday>true</MondayToFriday></OperatingProfile>').sourceCalendarLabel, /TermTime/);
const precedenceXml = xml
  .replace('<StandardService><Origin>A</Origin><Destination>B</Destination></StandardService><OperatingProfile><MondayToFriday>true</MondayToFriday>', '<StandardService><Origin>A</Origin><Destination>B</Destination></StandardService><OperatingProfile><MondayToFriday>true</MondayToFriday>')
  .replace('<JourneyPattern id="JP1">', '<JourneyPattern id="JP1"><OperatingProfile><Saturday>true</Saturday></OperatingProfile>')
  .replace('<OperatingProfile><MondayToFriday>true</MondayToFriday></OperatingProfile></VehicleJourney>', '<OperatingProfile><Sunday>true</Sunday></OperatingProfile></VehicleJourney>');
const precedence = parseTndsTransXchange(precedenceXml, { region: 'SE', sourceArchive: 'precedence.xml' });
assert.deepEqual(precedence.calendarEvidence[0].daysOfWeek, ['sunday'], 'VehicleJourney OperatingProfile overrides JourneyPattern and Service profiles');
assert.deepEqual(precedence.stopSchedules['021013518'].saturday, []);
assert.deepEqual(precedence.stopSchedules['021013518'].sunday, [1510]);

const mixedCalendarXml = `<TransXChange SchemaVersion="2.5"><Operators><Operator id="OP-MIX"><OperatorCode>OP-MIX</OperatorCode><TradingName>Mixed Operator</TradingName></Operator></Operators><Services><Service><ServiceCode>MIX</ServiceCode><LineName>MIX</LineName><RegisteredOperatorRef>OP-MIX</RegisteredOperatorRef><StandardService><Origin>Mixed origin</Origin><Destination>Mixed terminus</Destination><JourneyPatternRef>JP-MIX</JourneyPatternRef></StandardService></Service></Services><StopPoints><AnnotatedStopPointRef><StopPointRef>MIX-STOP</StopPointRef><CommonName>Mixed stop</CommonName></AnnotatedStopPointRef><AnnotatedStopPointRef><StopPointRef>MIX-END</StopPointRef><CommonName>Mixed terminus</CommonName></AnnotatedStopPointRef></StopPoints><JourneyPatternSections><JourneyPatternSection id="JPS-MIX"><JourneyPatternTimingLink><From><StopPointRef>MIX-STOP</StopPointRef></From><To><StopPointRef>MIX-END</StopPointRef></To><RunTime>PT10M</RunTime></JourneyPatternTimingLink></JourneyPatternSection></JourneyPatternSections><JourneyPatterns><JourneyPattern id="JP-MIX"><Direction>outbound</Direction><DestinationDisplay>Mixed terminus</DestinationDisplay><JourneyPatternSectionRefs>JPS-MIX</JourneyPatternSectionRefs></JourneyPattern></JourneyPatterns><VehicleJourneys><VehicleJourney><VehicleJourneyCode>MIX-SCHOOL</VehicleJourneyCode><JourneyPatternRef>JP-MIX</JourneyPatternRef><DepartureTime>07:00:00</DepartureTime><OperatingProfile><ServicedOrganisationDayType>Schooldays</ServicedOrganisationDayType><MondayToFriday>true</MondayToFriday></OperatingProfile></VehicleJourney><VehicleJourney><VehicleJourneyCode>MIX-NONSCHOOL</VehicleJourneyCode><JourneyPatternRef>JP-MIX</JourneyPatternRef><DepartureTime>07:30:00</DepartureTime><OperatingProfile><ServicedOrganisationDayType>Non-Schooldays</ServicedOrganisationDayType><MondayToFriday>true</MondayToFriday></OperatingProfile></VehicleJourney></VehicleJourneys></TransXChange>`;
const mixedCalendarTnds = parseTndsTransXchangeServices(mixedCalendarXml, { region: 'SE', sourceArchive: 'mixed-calendar.xml' });
assert.equal(mixedCalendarTnds.length, 2, 'mutually exclusive TNDS calendar profiles remain separate records');
assert.deepEqual(mixedCalendarTnds.map(service => service.calendarProfileId).sort(), ['non-school-day', 'school-day']);
assert.deepEqual(mixedCalendarTnds.map(service => service.stopSchedules['MIX-STOP'].monday).sort((a, b) => a[0] - b[0]), [[420], [450]], 'TNDS school and non-school schedules are not unioned');
assert.ok(mixedCalendarTnds.every(service => service.departureEvidenceByDay.monday[0].calendarProfileId === service.calendarProfileId));
const unsupportedXml = xml.replace(/<OperatingProfile><MondayToFriday>true<\/MondayToFriday><\/OperatingProfile>/g, '<OperatingProfile><SpecialDaysOperation><SpecialDay>Tuesday</SpecialDay></SpecialDaysOperation></OperatingProfile>');
const unsupported = parseTndsTransXchange(unsupportedXml, { region: 'SE', sourceArchive: 'unsupported.xml' });
assert.equal(unsupported.calendarEvidence[0].resolutionStatus, 'unresolved');
assert.match(unsupported.sourceWarnings.join(' '), /unsupported complex operating profile/);
assert.deepEqual(unsupported.stopSchedules['021013518'].monday, [], 'unsupported complex profiles never become fabricated weekday evidence');
const bods = [{ routeNumber: '999', operator: 'Other', direction: 'outbound', origin: 'X', destination: 'Y', stopSchedules: { '021013518': {} } }];
assert.equal(mergeBusTimetableSources({ bods, tnds: [parsed] }).length, 2);
assert.equal(mergeBusTimetableSources({ bods: [{ routeNumber: '231', operator: 'Example', direction: 'outbound', origin: 'A', destination: 'B', stopSchedules: parsed.stopSchedules }], tnds: [parsed] }).length, 1);
const multiPatternXml = `<TransXChange SchemaVersion="2.5"><Operators><Operator><TradingName>Pattern Operator</TradingName></Operator></Operators><Services><Service><ServiceCode>MULTI</ServiceCode><LineName>231</LineName><StandardService><Origin>A</Origin><Destination>C</Destination><JourneyPattern id="JP-OUT"><Direction>outbound</Direction><JourneyPatternSectionRefs>JPS-OUT</JourneyPatternSectionRefs></JourneyPattern><JourneyPattern id="JP-IN"><Direction>inbound</Direction><JourneyPatternSectionRefs>JPS-IN</JourneyPatternSectionRefs></JourneyPattern></StandardService></Service></Services><StopPoints><AnnotatedStopPointRef><StopPointRef>021013518</StopPointRef><CommonName>Woodside Road</CommonName></AnnotatedStopPointRef><AnnotatedStopPointRef><StopPointRef>STOP-B</StopPointRef><CommonName>Middle</CommonName></AnnotatedStopPointRef><AnnotatedStopPointRef><StopPointRef>STOP-C</StopPointRef><CommonName>Terminus</CommonName></AnnotatedStopPointRef></StopPoints><JourneyPatternSections><JourneyPatternSection id="JPS-OUT"><JourneyPatternTimingLink><From><StopPointRef>021013518</StopPointRef></From><To><StopPointRef>STOP-B</StopPointRef></To><RunTime>PT5M</RunTime></JourneyPatternTimingLink><JourneyPatternTimingLink><From><StopPointRef>STOP-B</StopPointRef></From><To><StopPointRef>STOP-C</StopPointRef></To><RunTime>PT7M</RunTime></JourneyPatternTimingLink></JourneyPatternSection><JourneyPatternSection id="JPS-IN"><JourneyPatternTimingLink><From><StopPointRef>STOP-C</StopPointRef></From><To><StopPointRef>STOP-B</StopPointRef></To><RunTime>PT7M</RunTime></JourneyPatternTimingLink></JourneyPatternSection></JourneyPatternSections><VehicleJourneys><VehicleJourney><JourneyPatternRef>JP-OUT</JourneyPatternRef><DepartureTime>08:00:00</DepartureTime><OperatingProfile><MondayToFriday>true</MondayToFriday></OperatingProfile></VehicleJourney><VehicleJourney><JourneyPatternRef>JP-IN</JourneyPatternRef><DepartureTime>09:00:00</DepartureTime><OperatingProfile><MondayToFriday>true</MondayToFriday></OperatingProfile></VehicleJourney></VehicleJourneys></TransXChange>`;
const multiPatterns = parseTndsTransXchangeServices(multiPatternXml, { region: 'SE', sourceArchive: 'fixture.xml' });
assert.equal(multiPatterns.length, 2);
const outboundPattern = multiPatterns.find(service => service.direction === 'outbound');
const inboundPattern = multiPatterns.find(service => service.direction === 'inbound');
assert.ok(outboundPattern && inboundPattern);
assert.deepEqual(outboundPattern.stopSchedules['021013518'].monday, [480]);
assert.deepEqual(outboundPattern.stopSchedules['STOP-B'].monday, [485]);
assert.deepEqual(outboundPattern.stopSchedules['STOP-C'].monday, [492]);
assert.deepEqual(inboundPattern.stopSchedules['STOP-B'].monday, [547]);
assert.deepEqual(inboundPattern.stopSchedules['STOP-C'].monday, [540]);
assert.deepEqual(inboundPattern.stopSchedules['STOP-C'].saturday, []);
assert.equal(outboundPattern.stopSchedules['STOP-C'].monday.includes(540), false);
assert.equal(inboundPattern.stopSchedules['STOP-C'].monday.includes(480), false);
assert.deepEqual(outboundPattern.routePatternStopIds, ['021013518', 'STOP-B', 'STOP-C']);
assert.deepEqual(inboundPattern.routePatternStopIds, ['STOP-C', 'STOP-B']);
assert.equal(outboundPattern.principalLocations.includes('Middle'), true);
assert.equal(inboundPattern.principalLocations.includes('Woodside Road'), false);
assert.throws(() => parseTndsTransXchange(multiPatternXml, { region: 'SE', sourceArchive: 'fixture.xml' }), /multiple planner pattern records/);
const mixedPatterns = parseTndsTransXchangeServices(multiPatternXml.replace('<RunTime>PT7M</RunTime></JourneyPatternTimingLink></JourneyPatternSection></JourneyPatternSections>', '</JourneyPatternTimingLink></JourneyPatternSection></JourneyPatternSections>'), { region: 'SE', sourceArchive: 'mixed-pattern.xml' });
assert.equal(mixedPatterns.length, 1);
assert.deepEqual(mixedPatterns[0].stopSchedules['021013518'].monday, [480]);
assert.deepEqual(mixedPatterns[0].stopSchedules['STOP-C'].monday, [492]);
assert.equal(mixedPatterns[0].tndsQuarantine.patterns.some(pattern => pattern.patternId === 'JP-IN'), true);
const rawIdPatterns = parseTndsTransXchangeServices(multiPatternXml.replace('<CommonName>Middle</CommonName>', ''), { region: 'SE', sourceArchive: 'raw-id.xml' });
const rawIdOutbound = rawIdPatterns.find(service => service.direction === 'outbound');
assert.deepEqual(rawIdOutbound.routePatternStopIds, ['021013518', 'STOP-B', 'STOP-C']);
assert.equal(rawIdOutbound.stopSchedules['STOP-B'].monday[0], 485);
assert.doesNotMatch(rawIdOutbound.principalLocations.join(', '), /STOP-B/);
assert.throws(() => parseTndsTransXchange(multiPatternXml.replace('</Services>', '<Service><ServiceCode>SECOND</ServiceCode></Service></Services>'), { region: 'SE', sourceArchive: 'multi.xml' }), /multiple Service records/);
const noTimingMultiStop = multiPatternXml.replace(/<JourneyPatternSections>[\s\S]*?<\/JourneyPatternSections>/, '<JourneyPatternSections></JourneyPatternSections>');
assert.throws(() => parseTndsTransXchange(noTimingMultiStop, { region: 'SE', sourceArchive: 'missing-timing.xml' }), /no deterministically identifiable affected StopPoint IDs/);
assert.doesNotThrow(() => parseTndsTransXchange(xml, { region: 'SE', sourceArchive: 'one-stop.xml' }));
const multiServiceXml = `<TransXChange SchemaVersion="2.5"><Operators><Operator id="OPA"><OperatorCode>OPA</OperatorCode><TradingName>Operator A</TradingName></Operator><Operator id="OPB"><OperatorCode>OPB</OperatorCode><TradingName>Operator B</TradingName></Operator></Operators><Services><Service id="SA"><ServiceCode>SA</ServiceCode><LineName>A1</LineName><RegisteredOperatorRef>OPA</RegisteredOperatorRef><StandardService><JourneyPattern id="JPA"><Direction>outbound</Direction><JourneyPatternSectionRefs>JSA</JourneyPatternSectionRefs></JourneyPattern></StandardService></Service><Service id="SB"><ServiceCode>SB</ServiceCode><LineName>B1</LineName><RegisteredOperatorRef>OPB</RegisteredOperatorRef><StandardService><JourneyPattern id="JPB"><Direction>outbound</Direction><JourneyPatternSectionRefs>JSB</JourneyPatternSectionRefs></JourneyPattern></StandardService></Service></Services><StopPoints><AnnotatedStopPointRef><StopPointRef>A-1</StopPointRef><CommonName>A origin</CommonName></AnnotatedStopPointRef><AnnotatedStopPointRef><StopPointRef>A-2</StopPointRef><CommonName>A terminal</CommonName></AnnotatedStopPointRef><AnnotatedStopPointRef><StopPointRef>B-1</StopPointRef><CommonName>B origin</CommonName></AnnotatedStopPointRef><AnnotatedStopPointRef><StopPointRef>B-2</StopPointRef><CommonName>B terminal</CommonName></AnnotatedStopPointRef></StopPoints><JourneyPatternSections><JourneyPatternSection id="JSA"><JourneyPatternTimingLink><From><StopPointRef>A-1</StopPointRef></From><To><StopPointRef>A-2</StopPointRef></To><RunTime>PT11M</RunTime></JourneyPatternTimingLink></JourneyPatternSection><JourneyPatternSection id="JSB"><JourneyPatternTimingLink><From><StopPointRef>B-1</StopPointRef></From><To><StopPointRef>B-2</StopPointRef></To><RunTime>PT13M</RunTime></JourneyPatternTimingLink></JourneyPatternSection></JourneyPatternSections><VehicleJourneys><VehicleJourney><VehicleJourneyCode>VA</VehicleJourneyCode><ServiceRef>SA</ServiceRef><JourneyPatternRef>JPA</JourneyPatternRef><DepartureTime>08:00:00</DepartureTime><OperatingProfile><MondayToFriday>true</MondayToFriday></OperatingProfile></VehicleJourney><VehicleJourney><VehicleJourneyCode>VB</VehicleJourneyCode><ServiceRef>SB</ServiceRef><JourneyPatternRef>JPB</JourneyPatternRef><DepartureTime>09:00:00</DepartureTime><OperatingProfile><MondayToFriday>true</MondayToFriday></OperatingProfile></VehicleJourney></VehicleJourneys></TransXChange>`;
const multiServices = parseTndsTransXchangeServices(multiServiceXml, { region: 'SE', sourceArchive: 'multi-service.xml' });
assert.equal(multiServices.length, 2);
assert.equal(multiServices[0].operator, 'Operator A'); assert.equal(multiServices[1].operator, 'Operator B');
assert.deepEqual(Object.keys(multiServices[0].stopSchedules).sort(), ['A-1', 'A-2']);
assert.deepEqual(Object.keys(multiServices[1].stopSchedules).sort(), ['B-1', 'B-2']);
assert.deepEqual(multiServices[0].stopSchedules['A-2'].monday, [491]);
assert.deepEqual(multiServices[1].stopSchedules['B-2'].monday, [553]);
assert.notEqual(multiServices[0].id, multiServices[1].id);
assert.throws(() => parseTndsTransXchange(multiServiceXml), /multiple Service records/);
const conflictXml = multiServiceXml.replace('<JourneyPatternRef>JPB</JourneyPatternRef><DepartureTime>09:00:00', '<JourneyPatternRef>JPA</JourneyPatternRef><DepartureTime>09:00:00');
assert.throws(() => parseTndsTransXchangeServices(conflictXml), /conflicting ServiceRef/);
const ambiguousXml = multiServiceXml.replace(/<ServiceRef>SA<\/ServiceRef>/, '').replace(/<ServiceRef>SB<\/ServiceRef>/, '').replace(/<JourneyPatternRef>JP[AB]<\/JourneyPatternRef>/g, '<JourneyPatternRef>UNKNOWN</JourneyPatternRef>');
assert.throws(() => parseTndsTransXchangeServices(ambiguousXml), /ambiguous service ownership/);
console.log('PASS TNDS parser, provenance, after-midnight and source merge tests.');
