import assert from 'node:assert/strict';
import path from 'node:path';import fs from 'node:fs';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium}=require('playwright');
const url=process.env.TPT_REVIEW_URL||'http://127.0.0.1:8772/modules/bus/index.html';
const browser=await chromium.launch({headless:true}),page=await browser.newPage({acceptDownloads:true}),result={url,checks:{},console:[],errors:[]};
page.on('console',m=>{if(['error','warning'].includes(m.type()))result.console.push(m.text());});page.on('pageerror',e=>result.errors.push(e.message));
try{
 await page.route('**/api/interpreter*',route=>route.fulfill({contentType:'application/json',body:JSON.stringify({elements:[{type:'node',id:1,lat:52.3971,lon:0.2678,tags:{name:'Fore Hill','naptan:AtcoCode':'0500EELYY096','naptan:Indicator':'near','naptan:StopArea':'fore-hill'}},{type:'node',id:2,lat:52.3972,lon:0.2676,tags:{name:'Fore Hill','naptan:AtcoCode':'0500EELYY097','naptan:Indicator':'opp','naptan:StopArea':'fore-hill'}}]})}));
 await page.route('**/table/v1/**',async route=>{const count=new URL(route.request().url()).pathname.split(';').length;await route.fulfill({contentType:'application/json',body:JSON.stringify({code:'Ok',distances:[Array.from({length:count},(_,i)=>i?100+i*10:0)],durations:[Array.from({length:count},(_,i)=>i?75+i*5:0)]})});});
 await page.goto(url,{waitUntil:'domcontentloaded',timeout:30000});const notice=page.getByRole('button',{name:'Open the page'});if(await notice.count())await Promise.all([page.waitForNavigation({waitUntil:'domcontentloaded'}),notice.click()]);
 await page.waitForSelector('.leaflet-container');result.checks.map=true;
 await page.getByLabel('Project/site name').fill('Bus reset smoke');await page.getByLabel('UK address or postcode').fill('CB7 4AH');await page.getByRole('button',{name:'Find address'}).click();await page.waitForSelector('#searchResults button');await page.locator('#searchResults button').first().click();assert.equal(await page.getByRole('button',{name:'Confirm site'}).isEnabled(),true);result.checks.confirmGate=true;await page.getByRole('button',{name:'Confirm site'}).click();await page.getByRole('button',{name:'Find nearby stops'}).click();await page.waitForFunction(()=>/candidate stops ready|discovery failed|zero stops/i.test(document.querySelector('#stopStatus')?.textContent||''),null,{timeout:50000});
 const rows=page.locator('#stopRows tr[data-stop-id]');assert.ok(await rows.count()>0);result.checks.stops=await rows.count();result.checks.routing=/routed|estimated/i.test(await page.locator('#stopRows').innerText());result.checks.separateDirections=new Set(await rows.locator('td:nth-child(3)').allTextContents()).size>1;
 await page.getByRole('button',{name:'Research & Library'}).click();const [requestDownload]=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:'Export bus research request'}).click()]);const request=JSON.parse(fs.readFileSync(await requestDownload.path(),'utf8'));assert.match(request.task,/research every selected bus stop/i);assert.match(request.task,/do not ask/i);result.checks.selfInstructing=true;
 await page.locator('#importResearch').setInputFiles(path.resolve('modules/bus/tests/fixtures/sample-completed-research.json'));await page.waitForFunction(()=>/Import complete/i.test(document.querySelector('#researchStatus')?.textContent||''));result.checks.import=true;result.checks.library=/stop–route relationships/.test(await page.locator('#knowledgeStatus').innerText());
 await page.getByRole('button',{name:'Outputs'}).click();const [docx]=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:'Download Word tables'}).click()]);result.checks.docx=(await docx.suggestedFilename()).endsWith('.docx');const [csv]=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:'Download CSV tables'}).click()]);result.checks.csv=(await csv.suggestedFilename()).endsWith('.csv');
 assert.equal(result.errors.length,0);console.log(JSON.stringify(result,null,2));
}finally{await browser.close();}
